= vol
:caution-caption: â˜¡ CAUTION
:important-caption: â— IMPORTANT
:note-caption: ðŸ›ˆ NOTE
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:source-highlighter: pygments
:tip-caption: ðŸ’¡ TIP
:toc-placement: preamble
:toc:
:warning-caption: âš  WARNING

A minimal POSIX shell library to help manage Docker data volumes.

== Dependencies

[options="header"]
|===

| Conditions | Type | Name (URL) | Version constraint

| by necessity
| software
| https://www.docker.com[Docker]
| >=1.10

| by necessity
| software
| Any POSIX compliant shell. https://www.gnu.org/software/bash/[Bash] and http://www.linuxfromscratch.org/blfs/view/svn/postlfs/dash.html[(d)ash] should work.
| *

| by default
| software
| https://www.gnu.org/software/coreutils/coreutils.html[GNU Core utilities]
| 8.25

| optional
| software
| https://www.sudo.ws/[Sudo]
| 1.8

|===

== To install

Source the shell script library:

[source,sh]
----
. '/path/to/vol/*.sh'
----

You can then call the functions defined inside it.
You can place the sourcing statement in the shell's startup profile to always have it on hand.

== To use

=== Specify volume name(s)

To conveniently start a child shell from which you can reference one volume named `'db_data-vol'`, you may issue e.g.:

[source,sh]
----
env VOL='db_data-vol' sh
----

=== Create the data volume

[source,sh]
----
sudo docker volume create --name="$VOL"
----

== Examples

=== To copy a directory into a volume

For example, to copy the contents of `'/root/keystore/'` into a volume:

[source,sh]
----
sudo dir_out.sh '/root/keystore/' | sudo vol_in.sh "$VOL"
----

=== To extract an existing archive into a volume

[source,sh]
----
sudo vol_in.sh "$VOL" < 'htdocs-vol.tar'
----

=== To export a volume as a compressed archive to a host over SSH

[source,sh]
----
sudo vol_out.sh "$VOL" | lbzip2 | ssh 'your_remote_host' sh -c 'cat > '"$VOL"'.tar.bz2'
----

Instead of `lbzip2`, you may use any compression program compatible with GNU `tar`, such as `gzip` or `xz`.
